### PR TITLE
Remove unnecessary default user-entry for DES commands

### LINKED ISSUE #480: uo des_create issue
### Expected behavior

When I run uo des_create I expect the following line to work:

uo des_create -y systemparam.json -f example_project.json -n m3

### Actual behavior

I receive the following output with an error at the end:

> gl@hl-m2` Working % uo des_create -y sampleUO/systemparam.json -f sampleUO/example_project.json -n sampleUO/m3
> Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
> Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
> Checking system.....
> ...python found at /Applications/URBANoptCLI_0.13.0/gems/ruby/2.7.0/gems/urbanopt-cli-0.13.0/example_files/python_deps/Miniconda-4.12.0/bin/python
> ...pip found at /Applications/URBANoptCLI_0.13.0/gems/ruby/2.7.0/gems/urbanopt-cli-0.13.0/example_files/python_deps/Miniconda-4.12.0/bin/pip
> DEPENDENCIES RETRIEVED FROM FILE: [{:name=>"ThermalNetwork", :version=>"0.2.5"}, {:name=>"urbanopt-ditto-reader", :version=>"0.6.4"}, {:name=>"NREL-disco", :version=>"0.5.1"}, {:name=>"geojson-modelica-translator", :version=>"0.7.0"}]
> ...ThermalNetwork found with specified version 0.2.5
> ...urbanopt-ditto-reader found with specified version 0.6.4
> ...NREL-disco found with specified version 0.5.1
> ...geojson-modelica-translator found with specified version 0.7.0
> Usage: uo_des create-model [OPTIONS] SYS_PARAM_FILE GEOJSON_FEATURE_FILE
>                            [PROJECT_PATH]
> Try 'uo_des create-model -h' for help.
> 
> Error: Got unexpected extra argument (Park/Working/sampleUO/m3)

I tried using the --des-name flag and got the same issue

If I try to run without specifying the des directory name I get the following:

> gl@hl-m2 Working % uo des_create -y sampleUO/systemparam.json -f sampleUO/example_project.json        
> Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
> Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
> Error: option --des-name must be specified.

### Additional context

Mac, running uo cli 0.13.0

### PR DESCRIPTION
**Pull request by vtnate**
### Pull Request Description

`des_params` & `des_create` had unnecessarily required input that was confusing the GMT cli. Removing the additional default input from here allows the GMT cli to apply its own default entries the way we expect.

### Checklist (Delete lines that don't apply)

- [x] All ci tests pass (green)
- [x] An [issue](https://github.com/urbanopt/urbanopt-cli/issues) has been created (which will be used for the changelog)
- [x] This branch is up-to-date with develop

### CODE REVIEW

File: lib/uo_cli.rb [hunk 1]
```diff
@@ -375,11 +376,13 @@ def opt_des_params
             "Example: uo des_params --sys-param path/to/sys_params.json --feature path/to/example_project.json\n", type: String, required: true, short: :f
 
           opt :model_type, "\nSelection for which kind of DES simulation to perform\n" \
-            "Valid choices: 'time_series'", type: String, default: 'time_series'
```
Comment (vtnate) [inline lib/uo_cli.rb:378]: This `default` entry was the source of the problem. The GMT cli supplies its own default values, and our overrides were confusing it. Removing this allows the GMT expected behavior to happen.

File: lib/uo_cli.rb [hunk 2]
```diff
@@ -375,11 +376,13 @@ def opt_des_params
...
+            "Valid choices: 'time_series']\n" \
+            'If not specified, the default time_series simulation type will be used', type: String, short: :m
 
           opt :district_type, "\nSelection for which kind of district system parameters to generate\n" \
             "Example: uo des_params --sys-param path/to/sys_params.json --feature path/to/example_project.json --district-type 5G_ghe\n" \
-            'If not specified, the default 4G district type will be used', type: String, required: false, short: :t
+            "Available options are: ['4G', '5G_ghe']\n" \
```
Comment (vtnate) [inline lib/uo_cli.rb:384]: We should tell the user what their options are, instead of making them guess. 😞

File: lib/uo_cli.rb [hunk 3]
```diff
@@ -74,7 +74,7 @@ def initialize
       # Define creation commands
       def opt_create
         @subopts = Optimist.options do
-          banner "\nURBANopt #{@command}:\n \n"
+          banner "\nURBANopt create:\n \n"
```
Comment (vtnate) [inline lib/uo_cli.rb:77]: Not sure why `command` isn't being parsed in the banner, but it was just blank. By using a string primitive we can at least show the user where they are.

File: lib/uo_cli.rb [hunk 4]
```diff
@@ -545,7 +548,7 @@ def self.create_scenario_csv_file(feature_id)
           end
           # Rescue if json isn't a geojson feature_file
         rescue NoMethodError
-          abort("\nOops! You didn't provde a valid feature_file. Please provide path to the geojson feature_file")
+          abort("\nOops! You didn't provide a valid feature_file. Please provide path to the geojson feature_file")
```
Comment (vtnate) [inline lib/uo_cli.rb:551]: I really like my plugin/pre-commit hook that finds typos and recommends fixes ❤️

**Review by kflemin — APPROVED** [review]
