### PR TITLE
error handling for non-US weatherfiles

### LINKED ISSUE #438: Improve error handling when attempting to use a non-US weather file
URBANopt run ends abruptly when a non-US weather file is used. The crash happens in the residential path in the Baseline mapper. Specifically this lookup returns nothing:
https://github.com/urbanopt/urbanopt-cli/blob/develop/example_files/mappers/Baseline.rb#L352-L361

Add a check to see whether this lookup is successful, and if not return an informative error to the user.

### PR DESCRIPTION
**Pull request by vtnate**
### Pull Request Description

Raise an informative error if the weatherfile is not able to match to a known climate zone. This happens if a user tries to use a non-US weather file, and may also catch other errors in the weather file.

### Checklist (Delete lines that don't apply)

~- [ ] Unit tests have been added or updated~
- [ ] All ci tests pass (green) (not expected until #442 is merged, which is waiting on ditto-reader PRs [47, 48, & 50](https://github.com/urbanopt/urbanopt-ditto-reader/pulls))
- [x] An [issue](https://github.com/urbanopt/urbanopt-cli/issues) has been created (which will be used for the changelog)
- [x] This branch is up-to-date with develop

### CODE REVIEW

File: spec/uo_cli_spec.rb [hunk 1]
```diff
@@ -294,15 +296,15 @@ def select_measures(test_dir, measure_name_list, workflow = 'base_workflow.osw',
...
-      # use this to test both opendss and disco workflows
-      system("#{call_cli} create --project-folder #{test_directory_elec} --disco")
-      delete_directory_or_file(test_directory_pv)
-      system("#{call_cli} create --project-folder #{test_directory_pv} --photovoltaic")
+    #   delete_directory_or_file(test_directory_elec)
+    #   # use this to test both opendss and disco workflows
+    #   system("#{call_cli} create --project-folder #{test_directory_elec} --disco")
+    #   delete_directory_or_file(test_directory_pv)
+    #   system("#{call_cli} create --project-folder #{test_directory_pv} --photovoltaic")
     end
```
Comment (kflemin) [inline spec/uo_cli_spec.rb:308]: is this meant to be commented out?

**Review by kflemin — APPROVED** [review]

File: spec/uo_cli_spec.rb (hunk 1 above)
Comment (vtnate) [reply spec/uo_cli_spec.rb:308]: Ugh, no. Thank you!
