### PR TITLE
Opendss time fix

### LINKED ISSUE #286: fix issues when running opendss simulations
- Flags for setting the time period of the opendss simulation ( "-a" and "-n" ) are not working. 

-  Simulation fail when using the config file

### PR DESCRIPTION
**Pull request by tanushree04**
### Pull Request Description

The OpenDSS run cli command has additional arguments to indicate the start and end date of simulation. In the current implementation a user can indicate the start/end date as well as time. Adding the time argument separated by a space from the date was throwing an error in windows for an extra argument.
The start/end date and time are not added as separate arguments. There are passed on to the ditto cli, where they are combined before being added to the config file to run the simulation.

To test: 

pip install -e {local ditto reader repo on opendss_time_fix branch}
bundle exec uo opendss -s {path to scenario} -f {path to geojson} --start-date "2017/01/01" --start-time "01:00:00"--end-time "2017/01/02" --end-time "01:00:00"

### Checklist (Delete lines that don't apply)

- [x] Unit tests have been added or updated
- [ ] All ci tests pass (green)
- [x] An [issue](https://github.com/urbanopt/urbanopt-cli/issues) has been created (which will be used for the changelog)
- [x] This branch is up-to-date with develop

### CODE REVIEW

**Comment by tanushree04** [comment]
I am able to get the tests to pass locally, since I am using the pip install -e (local branch of ditto reader) and run with the changes made. But the CI is testing it with the ditto reader released version and is failing.

File: lib/uo_cli.rb [hunk 1]
```diff
@@ -192,15 +192,25 @@ def opt_opendss
           "Optional, defaults to analog of simulation timestep set in the FeatureFile\n" \
           "Example: uo opendss --scenario baseline_scenario.csv --feature example_project.json --timestep 15", type: Integer, short: :t
 
-          opt :start_time, "\nBeginning of the period for OpenDSS analysis\n" \
+          opt :start_date, "\nBeginning date for OpenDSS analysis\n" \
+          "Optional, defaults to beginning of simulation date\n" \
+          "Example: uo opendss --scenario baseline_scenario.csv --feature example_project.json --start-date '2017/01/15'" \
+          "Ensure you have quotes around the date", type: String
```
Comment (vtnate) [inline lib/uo_cli.rb:198]: Do we still need quotes since we've eliminated the spaces?

File: lib/uo_cli.rb [hunk 2]
```diff
@@ -192,15 +192,25 @@ def opt_opendss
...
+          opt :start_time, "\nBeginning time for OpenDSS analysis\n" \
           "Optional, defaults to beginning of simulation time\n" \
-          "Example: uo opendss --scenario baseline_scenario.csv --feature example_project.json --start-time '2017/01/15 01:00:00'\n" \
-          "Ensure you have quotes around the timestamp, to allow for the space between date & time.", type: String
+          "Example: uo opendss --scenario baseline_scenario.csv --feature example_project.json --start-time '01:00:00'\n" \
+          "Ensure you have quotes around the time.", type: String
+
+          opt :end_date, "\End date for OpenDSS analysis\n" \
+          "Optional, defaults to end of simulation date\n" \
+          "Example: uo opendss --scenario baseline_scenario.csv --feature example_project.json --end-date '2017/01/16'" \
```
Comment (vtnate) [inline lib/uo_cli.rb:207]: Quotes necessary around date/time values?

**Review by vtnate — APPROVED** [review]
This looks rad. Need to figure out my native gem problem before manual testing, but the code looks good.

**Comment by kflemin** [comment]
@tanushree04 , @vtnate I made a few small changes to remove quotes and explicitly define the shortnames...this works on my local computer.  look good to you?

**Comment by vtnate** [comment]
> @tanushree04 , @vtnate I made a few small changes to remove quotes and explicitly define the shortnames...this works on my local computer. look good to you?

I made one more small change to the command instruction text. LGTM

**Comment by vtnate** [comment]
@tanushree04 I think the start date/times are clear with what you've got. Looks great!
